### ISSUE TITLE
 Error Mining Silver Vein

### ISSUE THREAD

**Issue by SavedByGrace251** [WiseHorror/Veinmine#3]
First of all, love this mod.

Second of all, there seems to be a bug when attempting to mine Silver.  The mod seems to be working when mining most other things (Haven't tested against every possible resource) but not for silver.

Log output

`NullReferenceException: Object reference not set to an instance of an object
Stack trace:
WiseHorror.Veinmine.Patches.MineRock5_DamageArea_Prefix (MineRock5 __instance, HitData hit, System.Int32 hitAreaIndex, EffectList& ___m_destroyedEffect, EffectList& ___m_hitEffect, System.Single& __state, System.Boolean& __result) (at <61d31386b1f4413c9fc98c66dfae1c39>:0)
(wrapper dynamic-method) MineRock5.DMD<MineRock5::DamageArea>(MineRock5,int,HitData)
MineRock5.CheckSupport () (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
MineRock5.RPC_Damage (System.Int64 sender, HitData hit, System.Int32 hitAreaIndex) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
RoutedMethod2[T,U].Invoke (System.Int64 rpc, ZPackage pkg) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
(wrapper dynamic-method) MineRock5.DMD<MineRock5::Damage>(MineRock5,HitData)
(wrapper dynamic-method) Attack.DMD<Attack::DoMeleeAttack>(Attack)
Attack.OnAttackTrigger () (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
Humanoid.OnAttackTrigger () (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)
CharacterAnimEvent.OnAttackTrigger () (at <843a49d5cb48439fa5a62a7bcd81c2a9>:0)`

**Comment by WiseHorror** [comment]
Fixed in 1.2.6
