### ISSUE TITLE
doesn't work after one hit

### ISSUE THREAD

**Issue by ezJosque** [WiseHorror/Veinmine#5]
I'm 100% sure that I installed it correctly, I didn't change any settings, I enter the game, I try to break the mine by pressing the lalt button and the boom is not damaged after the first blow and the mine becomes unbreakable.

Can you help me plsssss !!!!!!!!!

**Comment by LordBeera** [comment]
yes it seems i have had the same issue, error in log shows 

[Error  : Unity Log] MissingFieldException: Field 'HitData.m_toolTier' not found.
Stack trace:
(wrapper dynamic-method) MineRock5.DMD<MineRock5::DamageArea>(MineRock5,int,HitData)
MineRock5.RPC_Damage (System.Int64 sender, HitData hit, System.Int32 hitAreaIndex) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
RoutedMethod`2[T,U].Invoke (System.Int64 rpc, ZPackage pkg) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
(wrapper dynamic-method) MineRock5.DMD<MineRock5::Damage>(MineRock5,HitData)
(wrapper dynamic-method) Attack.DMD<Attack::DoMeleeAttack>(Attack)
Attack.OnAttackTrigger () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Humanoid.OnAttackTrigger () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
CharacterAnimEvent.OnAttackTrigger () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)


I am running build 1.2.6 of veinmine

**Comment by AzumattDev** [comment]
Fixed https://github.com/WiseHorror/Veinmine/pull/8
