### ISSUE TITLE
Indestructible Ores!

### ISSUE THREAD

**Issue by callmekaiyo** [WiseHorror/Veinmine#7]
When you hit the vein once, it switches from it's initial 1 health state to it's normal 6,500, 300, etc. health. But then... No more damage can be done to it :/ Sadness envelopes me.

**Comment by danger229** [comment]
makzimus in one of the valheim modding discord fixed the mod up. i have uploaded it to here: https://drive.google.com/file/d/1u7znr-8-iXbyMdqNi3w7RjjN46ajahWh/view?usp=drive_link

**Comment by AzumattDev** [comment]
Fixed https://github.com/WiseHorror/Veinmine/pull/8
